<div style="margin-top: 30px;">
</div>

<div id="sub_contentscontainer">
<p><span class="subtitle">Disclaimer & Legal Notice</span></p>
<p><b>Welcome to Insurance Filings, hereinafter "InsFilings", and InsFilings.com, also collectively referred to below as the "web site", where individual consumers and small business owners can research and shop for various insurance products.</b></p>

<p><b>InsFilings.com's materials and information are provided based on your acceptance of the terms and conditions below.</b></p>

<p><b>Please read the following terms and conditions carefully before using this web site or any of our other associated web sites.</b>
    You should review these terms and conditions regularly as they may change at any time at our sole discretion. The following terms and conditions apply to all of our web sites, including any web sites owned, operated or sponsored by any of our subsidiaries or affiliates, furthermore we may add to or supersede certain provisions of these terms and conditions with other provisions located in other sections found in any of our web sites.</p>

<p><b>Agreeing to these Terms of Use constitutes a contract between you and InsFilings and, where applicable, between you and this web site, or any associated site, wherein you may use the hardware, software, or services provided within the parameters of the agreement. You agree to provide true, accurate, current and complete information on this website. If you do not agree with these Terms of Use in full, including our Privacy Policy, as provided below and at our Privacy Policy, then you are not authorized to use any service of this website, and you should not provide any information therein.</b></p>

<p>&nbsp;</p>

<p><span class="subtitle_s"> 0. Age Restriction</span></p>

    <p>
        Currently, you must be eighteen (18) years of age or older to use this website, and if you are under the age of 18, you are hereby expressly notified that you are not permitted to provide any information through this website, for any purpose, including seeking insurance information or services. InsFilings is not responsible for monitoring or seeking verification of user qualification or age.
    </p>

<p><span class="subtitle_s"> 1. Liability</span></p>

    <p>
        UNDER NO CIRCUMSTANCES SHALL WE BE LIABLE FOR ANY DIRECT OR INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES THAT MAY ARISE FROM YOUR USE OF, OR INABILITY TO USE, THIS WEB SITE. Some jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages. In such jurisdictions, our liability is limited to the greatest extent permitted by law.
    </p>
        
    <p>
        THIS WEB SITE CONTENT IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
    </p>

<p><span class="subtitle_s">2. We Do Not Have Responsibility for Links to Third Party Content</span></p>

    <p>
        LINKS TO THIRD PARTY WEB SITES ARE PROVIDED FOR YOUR CONVENIENCE AND INFORMATION ONLY. THE CONTENT IN ANY LINKED WEB SITES IS NOT UNDER OUR CONTROL AND WE ARE NOT RESPONSIBLE FOR IT.
    </p>
    
    <p>
        LINKS TO THIRD PARTY WEB SITES ARE PROVIDED FOR YOUR CONVENIENCE AND INFORMATION ONLY. THE CONTENT IN ANY LINKED WEB SITES IS NOT UNDER OUR CONTROL AND WE ARE NOT RESPONSIBLE FOR IT.
    </p>

<p><span class="subtitle_s">3. Privacy/Treatment of Information or Data Transmitted via web site</span></p>

    <p>
        Personal information transmitted to us will be treated in accordance with our <a href="<?php echo base_url();?>about/privacy">Privacy Policy.</a> Insurance policies are issued by insurance carriers and the underwriting dept.  InsFilings is not liable for the acts of insurance carriers and providers that result in the change or amendment of policies.  The Company and website, as well as any representative thereof,  fully discloses all the risks associated with insurance products being offered and only helps clients to make informed decisions.  
    </p>
    
<p><span class="subtitle_s">4. Policy Qualifications and Requirements - [LIFE INSURANCE ONLY]</span></p>

    <p>
        ANY INFORMATION THAT YOU PROVIDE ON THIS WEBSITE FOR THE PURPOSE OF OBTAINING INFORMATION REGARDING A POTENTIAL INSURANCE POLICY, IS STILL SUBJECT TO THE RESULTS OF LAB RESULTS THAT ARE PART OF THE REQUIREMENTS FOR QUALIFICATION.
    </p>
    
    <p>
        InsFilings, the web site, and brokers, will in no way be held liable for any potential policies that are generated by preliminary information that is given to all above parties. 
    </p>

    <p>
        Furthermore, I understand that carriers will also check my driving record with the Dept of Motor Vehicles and also take into account any dangerous hobbies I may be engaged in. Therefore, I understand that in any and all cases I am liable for my own answers and actions in regard to any information I give to InsFilings, the web site, and brokers thereof. 
    </p>
  

</div>

