<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23115371-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

    <div style="float: left;">
        <a style="float:left;position:relative; top:10px; margin-right:25px;" href="<?php echo base_url();?>">
            <img border="0" src="<?php echo base_url();?>images/logo.png" />
        </a>
    </div>

   <div id="phone-number"></div>

    <div id="topMenuContainer">
        <a class="life" href="<?php echo base_url();?>life/life-insurance-overview"><img src="<?php echo base_url();?>images/menu/menu_life.png" alt="Life" /></a>
        <div class="divider">|</div>
        <a class="health" href="<?php echo base_url();?>health/health-insurance-overview"><img src="<?php echo base_url();?>images/menu/menu_health.png" alt="Health" /></a>
        <div class="divider">|</div>
        <a class="business "href="<?php echo base_url();?>business/business-insurance-overview"><img src="<?php echo base_url();?>images/menu/menu_business.png" alt="Business" /></a>
        <div class="divider">|</div>
        <a class="house" href="<?php echo base_url();?>house/house-insurance-overview"><img src="<?php echo base_url();?>images/menu/menu_house.png" alt="House&nbsp;&amp;&nbsp;Apartment" /></a>
    </div>
    
   <div id="myaccount">
        <a href="<?php echo base_url();?>account/mylogin"><img src="<?php echo base_url();?>images/buttons/myaccount_btn.png" alt="My Account" /></a>
   </div>